version: '3'
services: 
  weatherapi:
    build: WeatherAPI/
    ports:
    - "8000:80"
    environment:
      ASPNETCORE_URLS: "http://+"
      ASPNETCORE_ENVIRONMENT: Development
      
  frontend:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./:/path/to/cache
    depends_on:
      - weatherapi
    ports:
      - "4000:4000"